[build.environment]
  # https://docs.netlify.com/configure-builds/environment-variables/#build-metadata
  NEXT_PUBLIC_DEPLOY_CONTEXT = "${CONTEXT}"

[build]
  command = "pnpm build"
  publish = ".next/static"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self'"
    X-Content-Type-Options = "nosniff"
