[build.environment]
  # https://docs.netlify.com/configure-builds/environment-variables/#build-metadata
  NEXT_PUBLIC_DEPLOY_CONTEXT = "${CONTEXT}"

[build]
  command = "pnpm build"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self'"
    X-Content-Type-Options = "nosniff"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
