export const KERNEL_FOUNTAIN_DELAY = 1000;
export const KERNEL_FOUNTAIN_DURATION = 12000;
export const KERNEL_FOUNTAIN_KERNEL_COUNT = 100;

const FRAME_RATE = 60;
export const KERNEL_FOUNTAIN_INTERVAL = Math.floor(1000 / FRAME_RATE);
