export const DESKTOP_NAVIGATION_BAR_HEIGHT_PX = 135;
export const MOBILE_NAVIGATION_BAR_HEIGHT_PX = 98;

export const WINDOW_BREAKPOINT_WIDTH_PX = 860;
export const WINDOW_NARROW_WIDTH_PX = 375;

export const KERNEL_WIDE_SIZE_PX = 56;
export const KERNEL_NARROW_SIZE_PX = 42;

export const PRODUCTS_BREAKPOINT_PX = 700;

export const FOOTER_TOP_MARGIN_PX = 78;
