name: Execute end-to-end tests

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        required: true
        type: string
      preview_deployment_url:
        required: true
        type: string

permissions:
  statuses: write

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ inputs.commit_sha }}',
              state: 'pending',
              description: 'Executing end-to-end tests...',
              context: 'Execute end-to-end tests'
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}'
            });
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Execute Cypress test suite
        uses: cypress-io/github-action@v6
        id: cypress
        continue-on-error: true
        env:
          CYPRESS_BASE_URL: ${{ inputs.preview_deployment_url }}
        with:
          browser: chrome
          headed: false
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Update status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ steps.cypress.outcome }}' === 'success';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ inputs.commit_sha }}',
              state: success ? 'success' : 'failure',
              description: success ? 'Tests passed' : 'Tests failed',
              context: 'Execute end-to-end tests',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}'
            });
