name: Execute TypeScript type check

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
      - name: List images in src/images
        run: pnpm exec tsc --showConfig
      - name: Execute TypeScript type check
        run: pnpm type-check
